server:
  port: 8085
spring:
  application:
    name: "Authentication"
  devtools:
    add-properties: false
  r2dbc:
    url: "${SPRING_R2DBC_URL:r2dbc:postgresql://postgres-auth:5432/authentication_db}"
    username: "${SPRING_R2DBC_USERNAME:root}"
    password: "${SPRING_R2DBC_PASSWORD:password}"
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
  sql:
    init:
      mode: always
    data:
      r2dbc:
        repositories:
          enabled: true
adapters:
  r2dbc:
    host: postgres-auth
    port: 5432
    database: authentication_db
    schema: public
    username: root
    password: password
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8085"
jwt:
  secret: "mysuperlongsecretkeythatismorethan32bytes123!"
  expiration: 3600000